### ISSUE TITLE
Styling issues

### ISSUE THREAD

**Issue by Manas1820** [medicotary/Medicotary#70]
**Describe the bug**
<img width="765" alt="image" src="https://user-images.githubusercontent.com/53006261/142586690-1b1d8814-b498-47cf-9771-75f697a2bdce.png">

<img width="210" alt="image" src="https://user-images.githubusercontent.com/53006261/142586883-6267f722-f856-4439-82a3-cd00a3fd85a9.png">

**Comment by hayat-tamboli** [comment]
pehle img me kya issue hai, mujhe images dikh rahi hai
dusri ek dikkat hai, usko fix karta hu
@Manas1820
